import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const nunito = localFont({
  src: "./fonts/Nunito-Regular.ttf",
  variable: "--nunito",
  weight: "100 900",
});
const roboto = localFont({
  src: "./fonts/Roboto-Regular.ttf",
  variable: "--roboto",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Lidera Skills",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
