import type { Metadata } from "next";
import localFont from "next/font/local";
import Head from "next/head"; // Import Head component
import "./globals.css";
import { Header } from "./components/header";
import { Footer } from "./components/footer";

const nunito = localFont({
  src: "./fonts/Nunito-Regular.ttf",
  variable: "--nunito",
  weight: "100 900",
});
const roboto = localFont({
  src: "./fonts/Roboto-Regular.ttf",
  variable: "--roboto",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Lidera Skills",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description"/>
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={`${nunito.variable} ${roboto.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
